export { HelpCommand } from './help.command'
export { StartCommand } from './start.command'
export { MeCommand } from './settings/me.command'
export { setWebhook} from './settings/setWebhook'
export { SendMessage } from './methods/sendMessage'
export { getSettings } from './methods/getSettings'
export { SetChatCommand } from './settings/setChat.command'
export { InstanceCommand } from './settings/instance.command'
export { ResetChatCommand } from './settings/resetChat.command'
export { GetInstancesCommand } from './partner/getInstances.command'
export { NotificationsCommand } from './settings/notifications.command'
export { CreateInstanceCommand } from './partner/createInstance.command'
export { DeleteInstanceCommand } from './partner/deleteInstance.command'
export { ChangeInstanceCommand } from './settings/resetInstancenstance.command'
export { SetPartnerTokenCommand } from './partner/setPartnerToken.command'
